name: auto-sync

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # 允许手动触发

permissions:
  contents: write

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: 下载文件并存储到仓库目录
      - name: Sync Files to ModelScope
        env:
          TOKEN: ${{ secrets.MS_TOKEN }}
          NAME: ${{ secrets.GIT_NAME }}
          EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git clone https://oauth2:$TOKEN@www.modelscope.cn/studios/Genius-Society/wordlink.git ../ms_repo
          mv -f ./.github/restart.py ../
          rm -rf ./*.py ./*.txt ./LICENSE ./README.md ./.github ./.git ./.gitignore ./.gitattributes
          cp -rf ../ms_repo/.git ./
          if [ -n "$(git status --porcelain)" ]; then
            echo "Files are different, committing changes..."
            git config --global user.name "$NAME"
            git config --global user.email "$EMAIL"
            git add .
            git commit -m "Auto sync at $(date +%Y-%m-%d)"
            git push
            pip install modelscope
            python ../restart.py --token $TOKEN
          else
            echo "Files are the same, no changes."
          fi
